# Generated by Django 3.1.5 on 2021-01-15 11:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('passport_data', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Collective_contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_of_the_contract', models.IntegerField()),
                ('date_of_conclusion', models.DateField(default=datetime.date.today)),
                ('payments_for_insured_events', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('employee_full_name', models.CharField(max_length=120)),
                ('employee_risk_category', models.CharField(max_length=120)),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('full_name', models.CharField(max_length=120)),
                ('short_title', models.CharField(max_length=120)),
                ('adress', models.CharField(max_length=120)),
                ('bank_details', models.IntegerField()),
                ('company_specialization', models.CharField(max_length=120)),
                ('collective_contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.collective_contract')),
            ],
        ),
        migrations.AddField(
            model_name='collective_contract',
            name='employee_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.employee_category'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('age', models.IntegerField()),
                ('risk_category', models.CharField(max_length=120)),
                ('collective_contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.collective_contract')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='collective_contract_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.collective_contract'),
        ),
    ]
