# Generated by Django 3.1.5 on 2021-01-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20210115_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup_copy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('login', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
            ],
        ),
        migrations.RenameField(
            model_name='users',
            old_name='number',
            new_name='login',
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
