# Generated by Django 3.1.5 on 2021-01-16 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20210116_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backup_copy',
            old_name='login',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='backup_copy',
            name='password',
        ),
    ]
