# Generated by Django 3.1.5 on 2021-01-16 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20210116_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_category',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstapp.agent'),
            preserve_default=False,
        ),
    ]
