# Generated by Django 3.1.5 on 2021-01-16 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_employee_category_agent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_category',
            old_name='agent',
            new_name='agent_id',
        ),
    ]
